### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by gvsolgryn** [RoxCian/TheAsphyxiaOfEternity#1]
![image](https://user-images.githubusercontent.com/75806365/108863710-d5aa0b00-7634-11eb-938f-24ecb565b505.png)

This error occurs during plug-in loading.

**Comment by RoxCian** [comment]
You can remove `"target": "esnext"` in plugins/tsconfig.json

**Comment by gvsolgryn** [comment]
> You can remove `"target": "esnext"` in plugins/tsconfig.json

oh it work thank you!
